"""网络安全规则(10 条) —— 传输安全/证书校验/流量明文风险。"""

from __future__ import annotations

from ..core.engine import Rule
from ..models.insight import DifficultyLevel, InsightCategory, Severity

_CAT = InsightCategory.NETWORK
_REF_NET = ["https://mas.owasp.org/MASVS/05-masvs-maswe/"]

RULES = [
    Rule(
        id="NW-001",
        title="HTTP 明文接口",
        category=_CAT,
        severity=Severity.HIGH,
        confidence=0.95,
        patterns=[r"http://[a-z0-9]"],
        description="检测到 http:// 明文接口, 传输内容可被中间人窃听与篡改。",
        technical_context="提取字符串表中全部 URL 并按协议分类; 明文接口是抓包验证的第一优先级。",
        suggested_technique="plaintext-capture",
        next_steps=["枚举全部 http:// 接口", "评估传输数据的敏感级别", "修复: 全站 HTTPS + HSTS"],
        cwe_ids=["CWE-319"],
        masvs_refs=["MASVS-NETWORK-1"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-002",
        title="允许明文流量(usesCleartextTraffic)",
        category=_CAT,
        severity=Severity.HIGH,
        confidence=0.9,
        patterns=[r"usesCleartextTraffic\s*[:=]\s*true", r"cleartextTrafficPermitted"],
        description="Manifest/网络安全配置允许明文流量, 所有 http 请求都不会被系统拦截。",
        technical_context="确认 networkSecurityConfig 内容; 结合 NW-001 评估暴露面。",
        suggested_technique="basic-hook(URL.openConnection)",
        next_steps=["检查 network_security_config.xml", "修复: cleartextTrafficPermitted=false"],
        cwe_ids=["CWE-319"],
        masvs_refs=["MASVS-NETWORK-1"],
        references=_REF_NET,
        auto_fixable=True,
        fix_hint="AndroidManifest.xml: android:usesCleartextTraffic=\"false\"",
    ),
    Rule(
        id="NW-003",
        title="SSL Pinning 实现(可绕过验证)",
        category=_CAT,
        severity=Severity.INFO,
        confidence=0.9,
        patterns=[r"okhttp3\.CertificatePinner", r"certificatePinner", r"ssl\.pinning", r"TrustKit"],
        description="检测到证书绑定实现。属防护项; 授权测试中可用 ssl-bypass 套件验证其有效性。",
        technical_context="Hook CertificatePinner.check 与 TrustManagerImpl.checkTrustedRecursive 可验证绕过面。",
        suggested_technique="ssl-bypass",
        next_steps=["用 ssl-bypass 组合模板验证 pinning 覆盖度", "确认 pinning 失败时的降级行为"],
        cwe_ids=["CWE-295"],
        masvs_refs=["MASVS-NETWORK-2"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-004",
        title="信任所有证书(TrustAll TrustManager)",
        category=_CAT,
        severity=Severity.CRITICAL,
        confidence=0.95,
        patterns=[
            r"checkServerTrusted\s*\([^)]*\)\s*\{\s*\}",
            r"X509TrustManager",
            r"trustAllCerts",
        ],
        description="检测到自定义 X509TrustManager, 空实现等于信任任意证书, 可被中间人攻击。",
        technical_context="反编译确认 checkServerTrusted 是否为空; 运行时用自签证书即可复现 MITM。",
        suggested_technique="basic-hook(X509TrustManager)",
        next_steps=["确认空实现覆盖的范围", "修复: 移除自定义 TrustManager, 使用系统默认校验"],
        cwe_ids=["CWE-295"],
        masvs_refs=["MASVS-NETWORK-2"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-005",
        title="HostnameVerifier 校验缺失",
        category=_CAT,
        severity=Severity.CRITICAL,
        confidence=0.95,
        patterns=[r"HostnameVerifier", r"setHostnameVerifier", r"ALLOW_ALL_HOSTNAME_VERIFIER"],
        description="检测到自定义 HostnameVerifier, 若 verify 恒返回 true 则任意主机证书均可通过。",
        technical_context="Hook javax.net.ssl.HostnameVerifier.verify 观察返回值。",
        suggested_technique="return-modify(HostnameVerifier.verify)",
        next_steps=["确认 verify 实现", "修复: 使用 DefaultHostnameVerifier 或移除自定义实现"],
        cwe_ids=["CWE-295"],
        masvs_refs=["MASVS-NETWORK-2"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-006",
        title="WebView 加载明文/混合内容",
        category=_CAT,
        severity=Severity.MEDIUM,
        confidence=0.8,
        patterns=[r"setJavaScriptEnabled\s*\(\s*true", r"setMixedContentMode", r"loadUrl\(\s*['\"]http://"],
        description="WebView 开启 JS 且存在加载 http URL 或混合内容模式配置, 存在注入与流量劫持面。",
        technical_context="Hook WebView.loadUrl 打印全部加载地址; 检查 setMixedContentMode 参数。",
        suggested_technique="basic-hook(WebView.loadUrl)",
        next_steps=["枚举 WebView 加载的 URL", "修复: 强制 https + MIXED_CONTENT_NEVER_ALLOW"],
        cwe_ids=["CWE-79"],
        masvs_refs=["MASVS-NETWORK-1", "MASVS-PLATFORM-2"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-007",
        title="okhttp 明文/弱校验配置",
        category=_CAT,
        severity=Severity.MEDIUM,
        confidence=0.7,
        patterns=[r"okhttp3\.OkHttpClient", r"okhttp3\.Request"],
        check=lambda ctx: (
            ctx.find_evidence(r"okhttp3", limit=3)
            if ctx.has_signal(r"http://[a-z0-9]")
            else []
        ),
        description="检测到 OkHttp 网络栈且同时存在明文 URL, 疑似明文请求经过主网络栈发送。",
        technical_context="Hook okhttp3.OkHttpClient.newCall 可拦截全部请求(只读观察)。",
        suggested_technique="hashmap-trace(okhttp3.Request)",
        next_steps=["枚举 OkHttp 拦截器配置", "确认证书校验链完整性"],
        cwe_ids=["CWE-319"],
        masvs_refs=["MASVS-NETWORK-1"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-008",
        title="ws:// 明文 WebSocket",
        category=_CAT,
        severity=Severity.MEDIUM,
        confidence=0.9,
        patterns=[r"ws://[a-z0-9]", r"\"ws://"],
        description="检测到未加密 WebSocket 连接, 长连接消息可被窃听。",
        technical_context="Hook OkHttp WebSocketListener / WebSocket.send 观察消息内容(只读)。",
        suggested_technique="basic-hook(WebSocket.send)",
        next_steps=["确认 ws 用途与消息敏感度", "修复: 改用 wss://"],
        cwe_ids=["CWE-319"],
        masvs_refs=["MASVS-NETWORK-1"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-009",
        title="敏感参数出现在 URL 查询串",
        category=_CAT,
        severity=Severity.MEDIUM,
        confidence=0.75,
        patterns=[r"[?&](token|password|passwd|sessionid|session_id)=", r"[?&](access_token|auth)"],
        description="检测到 token/password 等敏感字段以查询串形式出现在 URL 中, 会被日志/代理/历史记录留存。",
        technical_context="Hook URL/Request 构造点确认参数流转。",
        suggested_technique="hashmap-trace(请求参数组装)",
        next_steps=["枚举带敏感参数的接口", "修复: 敏感数据移入请求体并加密"],
        cwe_ids=["CWE-598"],
        masvs_refs=["MASVS-NETWORK-1"],
        references=_REF_NET,
    ),
    Rule(
        id="NW-010",
        title="代理/VPN 检测(抓包对抗提示)",
        category=_CAT,
        severity=Severity.INFO,
        confidence=0.85,
        patterns=[r"getDefaultProxy", r"isProxyEnabled|proxyHost|system\.getproperty\(.{0,20}proxy", r"VPN\.prepare|VpnService"],
        description="检测到代理/VPN 检测逻辑, 会阻断授权测试环境的抓包链路。",
        technical_context="Hook System.getProperty('http.proxyHost') 返回 null 或 return-modify 相关检测方法可放行抓包。",
        suggested_technique="return-modify(代理检测方法)",
        next_steps=["定位代理检测实现", "授权测试中用 return-modify 放行"],
        cwe_ids=["CWE-693"],
        masvs_refs=["MASVS-RESILIENCE-2"],
        references=_REF_NET,
    ),
]
