"""
JavaScript/TypeScript 安全规则库

包含 JS 特有的误报规则和安全模式定义
"""

from .rules import (
    JS_SECURITY_RULES,
    JS_FALSE_POSITIVE_RULES,
    JS_SECURITY_GUARD_PATTERNS,
    JS_RULES_INDEX,
    FRAMEWORK_PATTERNS,
    XSS_ENHANCED_RULES_V230,
    PROTO_POLLUTION_ENHANCED_V230,
    INJECTION_ENHANCED_V230,
    SECRETS_ENHANCED_V230,
    UNSAFE_DOM_ENHANCED_V230,
    TYPESCRIPT_RULES_V230,
)

__all__ = [
    "JS_SECURITY_RULES",
    "JS_FALSE_POSITIVE_RULES",
    "JS_SECURITY_GUARD_PATTERNS",
    "JS_RULES_INDEX",
    "FRAMEWORK_PATTERNS",
    "XSS_ENHANCED_RULES_V230",
    "PROTO_POLLUTION_ENHANCED_V230",
    "INJECTION_ENHANCED_V230",
    "SECRETS_ENHANCED_V230",
    "UNSAFE_DOM_ENHANCED_V230",
    "TYPESCRIPT_RULES_V230",
]
