"""
规则模块
"""

from .java.rules import JAVA_FALSE_POSITIVE_RULES, JAVA_SECURITY_GUARD_PATTERNS

# JS 规则（可选）
try:
    from .js import JS_SECURITY_RULES, JS_FALSE_POSITIVE_RULES, JS_SECURITY_GUARD_PATTERNS
except ImportError:
    JS_SECURITY_RULES = []
    JS_FALSE_POSITIVE_RULES = []
    JS_SECURITY_GUARD_PATTERNS = {}

# Python 规则（v2.0）
try:
    from .python import PYTHON_SECURITY_RULES, PYTHON_RULES_INDEX
except ImportError:
    PYTHON_SECURITY_RULES = []
    PYTHON_RULES_INDEX = {}

__all__ = [
    "JAVA_FALSE_POSITIVE_RULES",
    "JAVA_SECURITY_GUARD_PATTERNS",
    "JS_SECURITY_RULES",
    "JS_FALSE_POSITIVE_RULES",
    "JS_SECURITY_GUARD_PATTERNS",
    "PYTHON_SECURITY_RULES",
    "PYTHON_RULES_INDEX",
]
